language: c

before_install:
        #- uname -a
        - cat /etc/*release | head
        #- ls
        - sudo apt-get update -qq
        - sudo apt-get install -qq wget unzip
        - sudo wget http://download.mono-project.com/repo/xamarin.gpg
        #- ls
        - sudo apt-key add xamarin.gpg
        #- sudo echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
        - sudo add-apt-repository "deb http://download.mono-project.com/repo/debian wheezy main"
        #- sudo ls /etc/apt
        - sudo apt-get update -qq
        #- mono --version
        - sudo apt-get install mono-devel
        - mono --version
        #- sudo apt-get install mono-complete
        - sudo apt-get install mono
        - mono --version
        - sudo mozroots --import --sync

script:
        - echo "Executing..."
        - mono --version
