language: c

before_install:
        - uname -a
        - cat /etc/*release | head
        - lsb_release -b
        - sudo wget http://download.mono-project.com/repo/xamarin.gpg
        - sudo apt-key add xamarin.gpg
        #- sudo echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
        - sudo ls /etc/apt
        - sudo apt-get update -qq
        - mono --version
        - sudo apt-get install -qq mono-devel
        - sudo apt-get install mono-complete
        - sudo mozroots --import --sync

script:
        - echo "Executing..."
        - mono --version
