language: c

before_install:
    # Identificando a distribuicao Linux para fins de LOG
    - cat /etc/*release | head
    - openssl version
    # Instalando o Mono
    #
    ##- chmod +x ./mono-debian-install.sh
    #- ./mono-debian-install.sh
    - source ./mono-debian-install.sh
    #
    # Instalando o KVM (K Version Manager)
    #
    ##- curl "https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh" | sh && source ~/.kre/kvm/kvm.sh
    ##
    - wget "https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh"
    - source ./kvminstall.sh
    - source ~/.kre/kvm/kvm.sh
    #
    # Instalando o K Runtime Environment (KRE)
    - kvm install 1.0.0-alpha3
    - kvm use 1.0.0-alpha3

script:
    - echo "Executing on mono version:"
    - mono --version
    - cd src/ > /dev/null
    - kpm restore --source "https://www.myget.org/F/aspnetmaster/api/v2"
    - k test
    - k run
    - kpm build
