language: c

before_install:
        - sudo wget http://download.mono-project.com/repo/xamarin.gpg
        - sudo apt-key add xamarin.gpg
        - sudo echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
        - sudo apt-get update -qq
        - sudo apt-get install -qq mono-devel
        - sudo apt-get install mono-complete
        - sudo mozroots --import --sync

script:
        - echo "Executing..."
        - mono --version
