language: c

before_install:
        # Identificando a distribuicao Linux para fins de LOG
        - cat /etc/*release | head
        # Utilitarios basicos para permitir o download e descompactacao de pacotes
        # necessarios para a preparacao do ambiente
        - sudo apt-get update -qq > /dev/null
        - sudo apt-get install -qq wget curl unzip > /dev/null
        # Baixando e instalando a Key para pacotes Xamarin do apt-get
        - sudo wget http://download.mono-project.com/repo/xamarin.gpg > /dev/null
        - sudo apt-key add xamarin.gpg > /dev/null
        # Adicionando o repositorio com pacotes do Mono atual disponibilizado pela Xamarin
        # ao apt-get e atualizando a lista para instalacao
        - sudo add-apt-repository "deb http://download.mono-project.com/repo/debian wheezy main" > /dev/null
        - sudo apt-get update -qq > /dev/null
        - sudo apt-get install -qq mono-devel > /dev/null
        # Atualizando os certificados SSL para habilitar as requisicoes HTTPS futuras
        - sudo mozroots --import --sync >/dev/null
        - sudo certmgr -ssl -m "https://myget.org"
        - sudo certmgr -ssl -m "https://geotrust.com"
        - sudo certmgr -ssl -m "https://rapidssl.com"
        - sudo certmgr -ssl -m "https://www.geotrust.com"
        - sudo certmgr -ssl -m "https://www.rapidssl.com"
        - sudo certmgr -ssl -m "https://www.myget.org"
        # Instalando o KVM (K Version Manager)
        - curl "https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh" | sh && source ~/.kre/kvm/kvm.sh
        # Instalando o K Runtime Environment (KRE)
        - kvm install 1.0.0-alpha3
        - kvm list
        - kvm use 1.0.0-alpha3
        - kvm list

script:
        - echo "Executing on mono version:"
        - mono --version
        - cd src/
        - ls
        - kpm help restore
        - kpm restore --source "https://www.myget.org/F/aspnetmaster/api/v2"
        - k run
        - kpm help build
        - kpm build
        - ls
