language: c

before_install:
        # Identificando a distribuicao Linux para fins de LOG
        - cat /etc/*release | head
        # Utilitarios basicos para permitir o download e descompactacao de pacotes
        # necessarios para a preparacao do ambiente
        - sudo apt-get update -qq > /dev/null
        - sudo apt-get install -qq wget unzip > /dev/null
        # Baixando e instalando a Key para pacotes Xamarin do apt-get
        - sudo wget http://download.mono-project.com/repo/xamarin.gpg > /dev/null
        - sudo apt-key add xamarin.gpg > /dev/nul
        # Adicionando o repositorio com pacotes do Mono atual disponibilizado pela Xamarin
        # ao apt-get e atualizando a lista para instalacao
        - sudo add-apt-repository "deb http://download.mono-project.com/repo/debian wheezy main" > /dev/null
        - sudo apt-get update -qq > /dev/null
        - sudo apt-get install -qq mono-devel > /dev/null
        # Atualizando os certificados SSL para habilitar as requisicoes HTTPS futuras
        - sudo mozroots --import --sync

script:
        - echo "Executing on:"
        - mono --version
