#!/usr/bin/env bash

echo "Build running..."

 echo "1. Install Mono >= 3.4.1 (3.8.0 recommended)"
 ./mono-install

echo "2. Install KVM"

echo "3. Install KRE"

echo "4. Prepare Procfile"
 ##    Ex: {
 ##      echo "web: k web" > $build_dir/Procfile
 ##    }
