#!/usr/bin/env bash

# x/deploy/kbuild <build-dir> <cache-dir>
build_dir=$1
cache_dir=$2

echo "Build running..."

echo "build_dir=$build_dir"
ls -R $build_dir

echo "1. Install Mono >= 3.4.1 (3.8.0 recommended)"
$build_dir/deploy/mono-install

echo "2. Install KVM"

echo "3. Install KRE"

echo "4. Prepare Procfile"
 ##    Ex: {
 ##      echo "web: k web" > $build_dir/Procfile
 ##    }
